### ISSUE TITLE
Proposal - store generated object field value to generate depended fields

### ISSUE THREAD

**Issue by yn-coder** [lk-geimfari/elizabeth#107]
This is a proposal.

Right now I type

    from elizabeth import Personal
    p = Personal('en')
    print( p.age() )
    print( p.age() )

And got output

    25
    40

Because age is generated by request and doesn't store in object `p`. What if I want to add the field `child_count` or `work experience`, depend on previously generated `age` value?

**Comment by lk-geimfari** [comment]
```python
from elizabeth import Personal
p = Personal('en')

saved_age = p.age()

do_something(saved_age)

```

**Comment by yn-coder** [comment]
:)
I mean store in object.

**Comment by lk-geimfari** [comment]
I understand and i think that it's not good idea. We have to many methods in all providers.

**Comment by yn-coder** [comment]
SO lib should be used for generate for unrelated, noise data.
If so, then proposal is unusual

**Comment by lk-geimfari** [comment]
@yn-coder You don't understand. Depended data is very cool, but i think that saving data in object is not good idea. We need something else.

**Comment by yn-coder** [comment]
Some cash?

**Comment by lk-geimfari** [comment]
@yn-coder Not yet.

**Comment by yn-coder** [comment]
@lk-geimfari 
> ...but i think that saving data in object is not good idea.

Why? Can you explain?

**Comment by lk-geimfari** [comment]
@yn-coder  Maybe I do not understand what you want.

You can try add your feature in your fork. If everything is okay we also add it to Elizabeth.

Maybe like that:
```python
from elizabeth import Personal

p = Personal(locale='en', dependent=True)
```

Give us example of how it will work.

**Comment by yn-coder** [comment]
I read your examples of Elizabeth usage, and now I think I understood.

`Person` object doesn't contain the generated data because you design it just as wrapper for generator funcion. `Person.age()` yeld the new value each time and tester could use it in a loop, without creating the object instance for next person.

Now I see the root of our miscommunication.

I'll prepare a some example for my proposal in a fork.

**Comment by lk-geimfari** [comment]
Exactly!

**Comment by yn-coder** [comment]
This is a simple illustration for my idea in my fork

https://github.com/yn-coder/elizabeth/commit/4fa723c36c375e10572f0469c504cf97dee29c72

Code is not production ready, just a demo.

**Comment by lk-geimfari** [comment]
Generally it looks good.

But i think that this
```python
    def __init__(self, locale='en'):
        """
        :param locale: Current language.
        """
        self.locale = locale
        self.data = pull('personal.json', self.locale)
        self.stored_age = 0
```
 Should be:

```python
    def __init__(self, locale='en'):
        """
        :param locale: Current language.
        """
        self.locale = locale
        self.data = pull('personal.json', self.locale)
        self._store = {'age': 0}
```

What do you think about it?

**Comment by lk-geimfari** [comment]
Now i see that it's really useful.

**Comment by yn-coder** [comment]
@lk-geimfari 
> What do you think about it?

You think `self._store` could be expanded for more parameters?

**Comment by lk-geimfari** [comment]
@yn-coder Yes, we can store in self._store other dependent data.

**Comment by yn-coder** [comment]
https://github.com/yn-coder/elizabeth/commit/d35218815649e0e54f60500bcdc6b40a8383048e

**Comment by lk-geimfari** [comment]
@yn-coder Great! Please, check it with [pycodestyle](https://github.com/PyCQA/pycodestyle)(or with similar tool) and send us PR.

**Comment by lk-geimfari** [comment]
Also don't forget about tests.

**Comment by yn-coder** [comment]
#109
