### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by yn-coder** [lk-geimfari/elizabeth#110]
Could eliz generate the random images? I do not found any (only `personal.avatar` linking).

Are you have a such plans?

**Comment by lk-geimfari** [comment]
@yn-coder Yes, this feature already realized.

```python
>>> from elizabeth import Internet
>>> 
>>> net = Internet()
>>> 
>>> net.image_placeholder()
'http://placehold.it/400x300'
>>> 
>>> net.image_placeholder(width='600', height='600')
'http://placehold.it/600x600'
>>> 
```
![](http://placehold.it/600x600)

**Comment by lk-geimfari** [comment]
@yn-coder We can also add support of [lorempixel.com/](http://lorempixel.com/) or other similar service.

**Comment by yn-coder** [comment]
And when download it by link?

**Comment by lk-geimfari** [comment]
Download? But why? This is a placeholder.

**Comment by yn-coder** [comment]
Not for html pages. I was thought about db loading with something like gravatars. In this case I need a bunch of image files generated.

**Comment by lk-geimfari** [comment]
We can add do `/other` folder with images, but i'm not sure that it's useful.

**Comment by yn-coder** [comment]
I mean `generated`. To make a **bunch** of files. May be where is a already existing tool somewhere?

**Comment by lk-geimfari** [comment]
@yn-coder Something like `pagan`?

**Comment by yn-coder** [comment]
https://github.com/daboth/pagan ?

Yes :)

**Comment by lk-geimfari** [comment]
@yn-coder We add something like it, but without third-party packages.

**Comment by lk-geimfari** [comment]
Current goal is full support of all 20 locales. From 0.4.0 we'll add more features.

**Comment by yn-coder** [comment]
Ok, it's  drag a some requirements to eliz.

Reject.
