### ISSUE TITLE
Add __str__ to providers.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#112]
How it will look:

```python
>>> from elizabeth import Personal
>>> p = Personal('pt-br')
>>> p
'Personal:pt-br:Brazilian Portuguese'

>>> Personal('en-gb')
'Personal:en-gb:British English'
```
Example available [here](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/core/elizabeth.py#L810)

**Comment by jlwt90** [comment]
I can help on this issue! Do you want to add __str__ to all providers or just the providers with locale?

**Comment by lk-geimfari** [comment]
@jlwt90 Thanks! Only for providers with locales, please.

**Comment by lk-geimfari** [comment]
Test
