### ISSUE TITLE
test_internet: dubious regexp

### ISSUE THREAD

**Issue by jwilk** [lk-geimfari/elizabeth#126]
`tests/test_data/test_internet.py` includes the following regexp fragment:
```
[$-_@.&+]
```
But `$-_` is a character range that includes digits, uppercase letter and a bunch of punctuation characters.
You probably wanted this instead:
```
[$_@.&+-]
```

The dubious regexp was found using [pydiatra](https://github.com/jwilk/pydiatra).

**Comment by lk-geimfari** [comment]
@jwilk Can you send us PR, please?
