### ISSUE TITLE
Date and time formats are missing for ko and jp locales.

### ISSUE THREAD

**Issue by wikkiewikkie** [lk-geimfari/elizabeth#131]
In data/ko/datetime.json and data/jp/datetime.json.  Example from en locale:

`  "formats": {
	"date": "%m/%d/%Y",
	"time": "%H:%M:%S"
  },`

**Comment by jlwt90** [comment]
Hi,

I updated in this commit.
https://github.com/jlwt90/elizabeth/commit/f0d25b0a1d3eba67d602f1359061a8c634aca253

However, I think I need to confirm with the locale contributors:

ko @redus 
```
"formats": {
    "date": "%Y.%m.%d",
    "time": "%H:%M:%S"
  },
```

jp @jasonwaiting-dev 
```
"formats": {
    "date": "%Y/%m/%d",
    "time": "%H:%M:%S"
  },
```

Thanks!

**Comment by lk-geimfari** [comment]
@redus @jasonwaiting-dev Please, look.

**Comment by jasonwaiting-dev** [comment]
@jlwt90 @lk-geimfari jp one is correct!

**Comment by redus** [comment]
For ko, "%Y/%m/%d" is used more often than "%Y.%m.%d" or "%Y-%m-%d", so could you please change to /?

**Comment by lk-geimfari** [comment]
@redus Fixed.
