### ISSUE TITLE
Update logo.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#135]
We expect a few more options. Then we will choose final logo.

---

First (by @beardedpayton):

![Cool logo](http://i.imgur.com/I4lZKjE.png)

---

**Comment by lk-geimfari** [comment]
@beardedpayton Hi! Here we can control our process.

**Comment by tobiasmarx** [comment]
Hey, if you need help, let me know.

**Comment by lk-geimfari** [comment]
@tobiasmarx Email me, please. likid.geimfari@gmail.com
