### ISSUE TITLE
Remove useless methods from the providers.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#142]
So, we need to find and remove useless methods.

For example: 
I once added the names of scientists to `science.json`, but now I'm not sure that these data can be useful.
So, what do you think about it?

**Comment by lk-geimfari** [comment]
@wikkiewikkie @Battleroid @Uncleleech Guys, please tell me what you think about this?

**Comment by Battleroid** [comment]
If it's rarely used I'd toss it out.

**Comment by wikkiewikkie** [comment]
If Elizabeth's purpose is to allow for bootstrapping databases and testing applications, we should focus on methods that meet those needs.  For those uses, I think Personal.fullname() would work in place of the scientist method.

**Comment by lk-geimfari** [comment]
@wikkiewikkie Totally agree with you! I deleted `scientist()`.
