### ISSUE TITLE
Separate providers by different file

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#156]
At this moment all our provider located in one file elizabeth/core/providers.py.

I propose to separate this files by providers.

This should looks like:

```
elizabeth/core/
.... personal.py
.... datetime.py
.... address.py
.... text.py
...
```

**Comment by lk-geimfari** [comment]
@wikkiewikkie What do you think?

**Comment by lk-geimfari** [comment]
Can it be helpful for editing and understanding of code of this library?

**Comment by wikkiewikkie** [comment]
@lk-geimfari It's not a big impact for me -- I use PyCharm and if you turn on show members, it is very easy to find a particular provider.

**Comment by lk-geimfari** [comment]
I opened this issue, but closed it at once . It seems that this is an unnecessary work.

**Comment by lk-geimfari** [comment]
@wikkiewikkie Do we need to change something in the structure of the project? Or is the current structure simple enough and convenient?
