### ISSUE TITLE
elizabeth.Network is missing

### ISSUE THREAD

**Issue by mpibpc-mroose** [lk-geimfari/elizabeth#161]
After upgrade to v 0.3.28 I cannot import Network anymore:
```
>> from elizabeth import __version__
>> __version__
'0.3.28'
>> from elizabeth import Network
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 'Network'
```
As it would break the API it should get added again.

**Comment by lk-geimfari** [comment]
@mpibpc-mroose Sorry. We forgotten to update documentation. The provider `Network` was removed. All methods from Network has been moved to `Internet()`
