### ISSUE TITLE
Broken links on file CONTRIBUTING.md

### ISSUE THREAD

**Issue by bbb1991** [lk-geimfari/elizabeth#180]
In file [CONTRIBUTING.md](https://github.com/lk-geimfari/elizabeth/blob/master/CONTRIBUTING.md) some links seems broken. When I tried to open inks, 404 error produced. Here is the links:
- [CURRENCY_SYMBOLS](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/intd/bus.py#L183)
- [ISBN_GROUPS](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/intd/code.py#L33)

**Comment by uvegla** [comment]
Hi @lk-geimfari, @bbb1991! I have created a small pull request to fix this. I have also removed the hard references to line numbers so it will not point to incorrect line once the files are updated and by names they are easy enough to find in my opinion.

**Comment by lk-geimfari** [comment]
@bbb1991 Fixed in #181  by @uvegla.

**Comment by bbb1991** [comment]
@uvegla great, thank you!
