### ISSUE TITLE
JP Locale is not supported

### ISSUE THREAD

**Issue by JuxhinDB** [lk-geimfari/elizabeth#184]
In the official docs for `0.4.0` it states that "JP" is a valid locale for Japan however when trying to use it, an `elizabeth.exceptions.UnsupportedLocale` exception is raised:

```
>>> import elizabeth
>>> from elizabeth import Personal
>>> Personal('jp')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/elizabeth/core/providers.py", line 868, in __init__
    self.data = pull('personal.json', self.locale)
  File "/usr/local/lib/python3.6/site-packages/elizabeth/utils.py", line 96, in pull
    raise UnsupportedLocale("Locale %s is not supported" % locale)
elizabeth.exceptions.UnsupportedLocale: 'Locale jp is not supported'
```

Confirming that I'm running 0.4.0 via pip freeze - `elizabeth==0.4.0`

Relevant documentation: http://elizabeth.readthedocs.io/en/latest/#locales

**Comment by lk-geimfari** [comment]
@JuxhinDB Sorry, we forget to update documentation. Use code `ja`, not `jp`.

**Comment by JuxhinDB** [comment]
No worries! Just double-checking. Thanks alot :-)
