### ISSUE TITLE
Need checking the correctness of the data.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#26]
It would be nice to check the correctness of the data for all locales. So, if you are a carrier of a language from list, then please help us.

List of locales whose data need to check:
- :es: - Español ([es](https://github.com/lk-geimfari/church/tree/master/church/data/es))
- :de: - Deutsch ([de](https://github.com/lk-geimfari/church/tree/master/church/data/de))
- :fr: - Français ([fr](https://github.com/lk-geimfari/church/tree/master/church/data/fr))
- :it: - Italiano ([it](https://github.com/lk-geimfari/church/tree/master/church/data/it))
- :brazil: - Português ([pt-br](https://github.com/lk-geimfari/church/tree/master/church/data/pt-br))
- :norway: - Norsk ([no](https://github.com/lk-geimfari/church/tree/master/church/data/no))
- :sweden: - Svenska ([sv](https://github.com/lk-geimfari/church/tree/master/church/data/sv))

---

P.S Thanks!

**Comment by polaroi8d** [comment]
Hey @lk-geimfari can i add the Hungarian version of this? :)

**Comment by lk-geimfari** [comment]
@polaroi8d Yes, of course! It's gread idea! If you want i can upload skeleton for `hu` locale. Thanks!

**Comment by lk-geimfari** [comment]
@polaroi8d I just now [added](https://github.com/lk-geimfari/church/tree/master/church/data/hu) a skeleton for `hu` locale.
