### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/elizabeth#48]
As we discussed earlier adding legacy `python` version support is not much of an effort. 
The main difficulty is the manual labour to ensure every `.decode()` and `.encode()` calls are in place.

However, there are several questions to answer:
- Is `python2` support even needed?
- How important it is?
- How should it be tested?

What do you think?

**Comment by lk-geimfari** [comment]
@sobolevn To be honest, I have no idea how to check it, but until this moment no one opened issue about this. Let's see what people think about this.

------
As for me, generally I use Python 3. So, if contributors think, that we needed the supporting of `Python 2`, then I have nothing against.

**Comment by aminalaee** [comment]
@lk-geimfari I've tested Python 2 and fixed some issues but Python 2 requires install functools32 when installing. Can we consider switching to setuptools?

**Comment by lk-geimfari** [comment]
@aminalaee I think that we will only focus on the Python 3.

**Comment by aminalaee** [comment]
@lk-geimfari Ok, I though it was to be done.

**Comment by lk-geimfari** [comment]
@aminalaee The advantage is that the library has no dependencies. If we wanna add support of Python 2 we need to add at least one requirement - `six`, and it's not good.
