### ISSUE TITLE
Solve the issues that arose after the renaming of the library.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#51]
The library has been renamed (I hope that this name is not offensive) and now we need to check all code lines of our library.

TODO:
- Check documentation.
- Check docstrings.

**Comment by Battleroid** [comment]
Submitted #52.

**Comment by lk-geimfari** [comment]
@Battleroid Thank you!

**Comment by Uncleleech** [comment]
Submitted #69, unsure if you guys wanted it or not so feel free to reject.
