### ISSUE TITLE
Test Path in MS Windows.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#55]
Today has been added class `Path` that provides methods and property for generate the dummy paths. I tested it only on Linux. It would be great if someone can run all tests on MS Windows.

Usage
```
>>> from elizabeth import Path

>>> path = Path()

>>> path.root
/
>>> path.home
/home/

>>> path.user(gender='female')
/home/mariko

>>> path.users_folder(user_gender='male')
/home/john/Documents

>>> path.dev_dir()
/home/fidelia/Development/Erlang

# etc.
```

**Comment by nebesnytihohod** [comment]
@lk-geimfari, after you fix the problem with the import Path, which we discussed, now
> from elizabeth import Path

run correctly.
I tested feature of generating sys.path.
Result:
```python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from elizabeth import Path
>>> path = Path()
>>> path.root
'С:\\'
>>> path.home
'С:\\Users\\'
>>> path.user(gender='female')
'С:\\Users\\Jeanice'
>>> path.user(gender='male')
'С:\\Users\\Dudley'
>>> path.users_folder(user_gender='male')
'С:\\Users\\Jerold\\Development'
>>> path.dev_dir(user_gender='female')
'С:\\Users\\Jack\\Development\\AutoIt'
>>> path.project_dir(user_gender='female')
'С:\\Users\\Alla\\Development\\Python\\insidious'
```

For Windows one of the backslash is superfluous.
I'll try to fix it.

**Comment by lk-geimfari** [comment]
@nebesnytihohod I thought that this format works with Windows. Are you sure that is format does not work?

**Comment by nebesnytihohod** [comment]
_Ooops... really..._
Now checked, and it turned out that in CLI in Windows-10, -7,  you can write path using the '\\\\', '/', '\\', '//'.
I have always thought, and in the Microsoft document it is written, that we should use only '\\\'.

Then the question is removed. :-)
