### ISSUE TITLE
Run tests on macOS

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#56]
I think that it's should work without problems, but i need make sure.

**Comment by seemethere** [comment]
Looks fine to me.
<img width="922" alt="screen shot 2016-12-19 at 9 38 14 pm" src="https://cloud.githubusercontent.com/assets/1700823/21339363/7c5ee904-c633-11e6-86d6-fb02dab7a797.png">

**Comment by lk-geimfari** [comment]
@seemethere Great job! Thanks you!
