### ISSUE TITLE
Add CNPJ and CPF generator to Brazil localization

### ISSUE THREAD

**Issue by martini97** [lk-geimfari/elizabeth#62]
Would you mind if I added a CPF (for person) and CNPJ (for companies) to the brazilian location?

**Comment by lk-geimfari** [comment]
@martini97 Can you show me examples?

**Comment by lk-geimfari** [comment]
@martini97 If find on wikipedia some information about CNPJ and CPF.

So... `CNPJ consists of a 14-digit number formatted as 00.000.000/0001-00`

It's can be generated using `identifier()` of `Personal()` provider or with `custom_code()` of `Code()` provider.

Using `identifier()`
```python
>>> from elizabeth import Personal
>>> p = Personal('pt-br')

>>> mask = "##.###.###/###1-##"
>>> p.identifier(mask=mask)
'97.370.304/1621-56'
>>> 
```
Using `custom_code()`:
```python
>>> from elizabeth import Code
>>> code = Code('pt-br')
 
>>> mask = "##.###.###/####-##"
>>> code.custom_code(mask=mask)
'48.613.965/8831-32'
```

Similarly for CPF.

**Comment by martini97** [comment]
@lk-geimfari both of these numbers ara CNPJ, have you already got a function for CPF?

It's a 11 digit code formated as 000.000.000-00

**Comment by martini97** [comment]
Also, both CPF and CNPJ requires some validations, some of the generated ones aren't valid.

**Comment by lk-geimfari** [comment]
This functions generate any code you want. Just use `mask="@#"`, where `@` is char and `#` is digit.

**Comment by martini97** [comment]
Yes, but it generates invalid CPF and CNPJ, to generate them it's needed to perform a modulo 11 calculation in a base number and add the result to it

**Comment by martini97** [comment]
I've this gist with an example for a function that generates it https://gist.github.com/martini97/c2266ed6efc420f3050cec3a0baebd43

**Comment by lk-geimfari** [comment]
@martini97 Okay, add it to `Code()` and don't forget write tests. Thank you!

**Comment by martini97** [comment]
Okay

**Comment by martini97** [comment]
Created the PR
