### ISSUE TITLE
Auto fetch science.json\article from Wikipedia

### ISSUE THREAD

**Issue by yn-coder** [lk-geimfari/elizabeth#65]
[science.json\article](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/data/en/science.json#L2) is a list of some articles from Wikipedia.

You can fetch it's automaticaly from Wiki Data by [group](https://en.wikipedia.org/wiki/Category:Mathematical_concepts), for example, in Elizabeth generating session. 

Is it idea?

**Comment by lk-geimfari** [comment]
@yn-coder Yeah, it's good idea but our priority is data generating. Articles are not worth such a complexity of the library.

**Comment by yn-coder** [comment]
:(

**Comment by lk-geimfari** [comment]
@yn-coder I'm sorry, but it requires too much effort.
