### ISSUE TITLE
Support for Declension

### ISSUE THREAD

**Issue by yn-coder** [lk-geimfari/elizabeth#66]
Support for [declension](https://en.wikipedia.org/wiki/Declension). This is very usefull for russian and some other languages.

I can suggest some examples for russian, if it would be helpfull.

For example from [address.json](https://github.com/lk-geimfari/elizabeth/blob/master/elizabeth/data/ru/address.json)

    "suffix": [
          "Аллея",
          "ул."
        ]

If I'll add the `бульвар` (Boulevard) to suffix list, then `Авангардная` from streets list will be incorrect - it should be `Авангардный`.

**Comment by lk-geimfari** [comment]
@yn-coder , So, i answer for your question in Russian.

В эту секцию не добавлено ничего кроме `Аллея` и `ул.` именно из-за проблем со склонением.

**Comment by yn-coder** [comment]
Понятно, коллега. Вы подумали об этом. В других языках не было таких запросов?

**Comment by lk-geimfari** [comment]
@yn-coder Я бы с радостью, но запросов не было а мои знания в других языках сильно ограничены. Суффиксы улиц не стоят того, чтобы ворошить весь код. Пусть их будет только два. Вариаций в итого все равно очень много.

**Comment by yn-coder** [comment]
`Авангардная площадь` еще можно :)

**Comment by lk-geimfari** [comment]
@yn-coder Можете добавить, сгенерировать 100 значений и посмотреть возникают ли ошибки, если нет, то без проблем.

**Comment by yn-coder** [comment]
Забуду. Надо эту задачу открыть

**Comment by lk-geimfari** [comment]
@yn-coder Я не забуду. Проверю сам.

**Comment by yn-coder** [comment]
Проверил, вроде звучит корректно. Хотя в наличном списке улиц есть например "Ярославское"

https://github.com/lk-geimfari/elizabeth/pull/68

**Comment by lk-geimfari** [comment]
С этим немного повременим. `ул.` и `Аллея`  подходят нормально и создают достаточное количество вариаций.
