### ISSUE TITLE
Problems with unicode on Windows.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#70]
JeStoneDev from a habr has following:
```python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from elizabeth import Personal
>>> user = Personal('is')
>>> for _ in range(0, 9):
...     print(user.full_name(gender='male'))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\mainj\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf0' in position 5: character maps to <undefined>
```
So, if your machine on Windows 10 then, please, try to fix it.

**Comment by mipaaa** [comment]
You should switch the console code page to UTF-8 before running such a code:

`C:\Test\Elizabeth **chcp 65001**
65001

C:\Test\Elizabeth **py**
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from elizabeth import Personal
>>> user = Personal('is')
>>> for _ in range(0, 4):
...     print(user.full_name(gender='male'))
...
Oddmar Sandrason
Þiðrandi Ófeigsson
Ljúfur Ófeigsson
Nikolai Skæringsson
>>>`

**Comment by lk-geimfari** [comment]
@mipaaa Thank you!
