### ISSUE TITLE
Why not contribute to faker instead of creating Yet Another lib ?

### ISSUE THREAD

**Issue by sametmax** [lk-geimfari/elizabeth#75]
Current we have the very popular and useful faker (https://github.com/joke2k/faker) to generate fixtures. Instead of splitting the FOSS effort, why not join forces ?

**Comment by lk-geimfari** [comment]
@sametmax Faker is not suitable for my tasks, when i start this project. You always can use Faker. The variety of themes and good.

**Comment by sametmax** [comment]
Then why didn't you not contribute to this project to make it suitable ? It's open source. What you are doing here is repeating something existing.

**Comment by lk-geimfari** [comment]
@sametmax As you say "it is open source".  If something has been created, it does not mean that it cannot be created better, right?

**Comment by Uncleleech** [comment]
@sametmax This library doesn't do the same thing as faker. I can see @lk-geimfari's point quite clearly. Also surely having more than one library allows for choice by the user? Perhaps there could be a comparison to faker in the readme so people do not get confused; the timings from #12 spring to mind.

**Comment by lk-geimfari** [comment]
@Uncleleech I will add full comparison of Elizabeth and Faker as soon as possible. I hope that i can do it tonight.
